#pragma once

#include "engine/ecs/components/Transform.h"
#include "engine/ecs/components/Sprite.h"
#include "engine/ecs/components/Tags.h"
#include "engine/ecs/components/Health.h"
#include "engine/ecs/components/PathFollow.h"
#include "engine/ecs/components/SpawnRequest.h"
#include "engine/ecs/components/Sprite.h"
#include "engine/ecs/components/Tags.h"
#include "engine/ecs/components/Transform.h"
#include "engine/ecs/components/WaveState.h"
#include "engine/ecs/components/Movement.h"
#include "engine/ecs/components/Shooting.h"
#include "engine/ecs/components/Targeting.h"
#include "engine/ecs/components/AudioClip.h"